### ISSUE TITLE
Ads Are Back

### ISSUE THREAD

**Issue by Nemisor** [apsun/SoundCloudAdAway#3]
As of the 2017.02.22 version, video/audio ads are playing again. Seems like they may have updated their API. Any assistance would be appreciated!

**Comment by apsun** [comment]
Alright, I'll take a look when I get the time (currently really busy with exams). Thanks for reporting.

**Comment by Nemisor** [comment]
Awesome! Thank you for not abandoning this project ^.^

**Comment by apsun** [comment]
Hmm, so I tried it out (with both 2017.02.22 and 2017.03.03) and I can't reproduce the problem, ad blocking seems to be working fine. Mind posting your Xposed logs and a logcat dump (`adb logcat -s "SoundCloudAdAway"`)? Thanks!

**Comment by Nemisor** [comment]
I'm embarrassed to admit... I forgot that my primary phone no longer has xposed, and noticed it there. My 5X still has xposed and it's fine there. Sorry, my friend ;/

**Comment by apsun** [comment]
Lol, no worries. Nice to know that the module still works after a year without any updates :-p
