### ISSUE TITLE
Ads not blocked in likes

### ISSUE THREAD

**Issue by Evox99** [apsun/SoundCloudAdAway#4]
I'm still getting a Sprint Verizon and squarespace audio ads in my likes stream

**Comment by apsun** [comment]
I will need more information than that to debug the problem. Can you please attach a logcat? (`adb logcat -s "SoundCloudAdAway"`) Thanks.

**Comment by Evox99** [comment]
I updated to latest version of soundcloud and the issue is resolved. Sorry for the trouble, and thank you so much for your hard work I cant thank you enough :)
