### ISSUE TITLE
Can this somehow be used on Android 7.1.1?

### ISSUE THREAD

**Issue by DissCent** [apsun/SoundCloudAdAway#5]
I have a Oneplus 3 and I'm really tired of SoundCloud's advertisements. I'd love to use SoundCloudAdAway, but since it requires the xposed framework, which is not available for Android N, there is no way I could use it, right?

**Comment by apsun** [comment]
Yes, you would have to wait for Xposed to be released for Nougat. This app does not work without Xposed.
